version: "3.9"
services:
  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: zaza
      MYSQL_DATABASE: svc_users
    volumes:
      - data-mysql:/var/lib/mysql
    restart: always
    networks:
      - spring

  postgres14:
    container_name: postgres14
    image: postgres:14-alpine
    ports:
      - "5532:5432"
    environment:
      POSTGRES_PASSWORD: zaza
      POSTGRES_DB: svc_courses
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  svc_users:
    container_name: svc_users
    image: brayanjsalcedo/svc_users:latest
    ports:
      - "8001:8001"
    env_file:
      - ./svc-users/.env
    networks:
      - spring
    depends_on:
      - mysql8
    restart: always

  svc_courses:
    container_name: svc_courses
    image: brayanjsalcedo/svc_courses:latest
    ports:
      - "8002:8002"
    env_file:
      - ./svc-courses/.env
    networks:
      - spring
    depends_on:
      - postgres14
    restart: always

volumes:
  data-mysql:
    name: data-mysql
  data-postgres:
    name: data-postgres
networks:
  spring: